language: swift
osx_image: xcode9.3

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace SwipeMenuViewController.xcworkspace -scheme SwipeMenuViewController CODE_SIGNING_REQUIRED=NO

